// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/quocdaitrn/cp-user/app/transport/gapi/grpcimpl"
	"github.com/quocdaitrn/cp-user/domain/service/serviceimpl"
	"github.com/quocdaitrn/cp-user/infra/adapters"
	"github.com/quocdaitrn/cp-user/infra/config"
	"github.com/quocdaitrn/cp-user/infra/providers"
	"github.com/quocdaitrn/cp-user/infra/repo/repoimpl"
	"github.com/quocdaitrn/golang-kit/validator"
)

// Injectors from wire.go:

func InitApplication(ctx context.Context) (*ApplicationContext, func(), error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	db, err := adapters.ProvideMySQL(configConfig)
	if err != nil {
		return nil, nil, err
	}
	userRepo := repoimpl.NewUserRepo(db)
	validatorValidator, err := validator.New()
	if err != nil {
		return nil, nil, err
	}
	userService := serviceimpl.NewUserService(userRepo, validatorValidator)
	logger := providers.ProvideLogger()
	authenticateClient, err := adapters.ProvideAuthClient(configConfig)
	if err != nil {
		return nil, nil, err
	}
	restAPIHandler := adapters.ProvideRoutes(userService, logger, configConfig, authenticateClient)
	restService, cleanup, err := adapters.ProvideRestService(configConfig, restAPIHandler)
	if err != nil {
		return nil, nil, err
	}
	userServiceServer := grpcimpl.NewGRPCServer(userService, logger, authenticateClient)
	grpcService, cleanup2, err := adapters.ProvideGRPCService(configConfig, userServiceServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	applicationContext := &ApplicationContext{
		ctx:         ctx,
		cfg:         configConfig,
		restService: restService,
		grpcService: grpcService,
	}
	return applicationContext, func() {
		cleanup2()
		cleanup()
	}, nil
}
